### ISSUE TITLE
Create from Skeleton

### ISSUE THREAD

**Issue by Praesidiarius** [OnePlc/PLC_X_Article_History#1]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Create from Skeleton. Is pretty much the same as contact history. you can view it, and you can also add it (same as contact history). fields for history form:
- date (date)
- supplier_idfs (select on Contact Module)
- article_idfs (hidden.link to article)
- comment (text / varchar 255)
- price ( currency / float )
- amount ( number / float )

**Comment by JBinggi** [comment]
module created, fields are created 5db5117 88a42469847188b8464718f51eedf49983235c83
